[package]
name = "slack_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-web = "4"
actix-rt = "2.10.0"
actix-web-actors = "4.3.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"

